module Types where

data Userid = Userid Integer deriving (Show, Eq)
data Username = Username String deriving (Show, Eq)
data Usercomment = Usercomment String deriving (Show, Eq)
data User = User Userid Username Usercomment deriving (Show, Eq)
data Domainid = Domainid Integer deriving (Show, Eq)
data Domainname = Domainname String deriving (Show, Eq)
data Domaincomment = Domaincomment String deriving (Show, Eq)
data Domain = Domain Domainid Domainname Domaincomment deriving (Show, Eq)
data Repoid = Repoid Integer deriving (Show, Eq)
data Reponame = Reponame String deriving (Show, Eq)
data Repocomment = Repocomment String deriving (Show, Eq)
data Repo = Repo Repoid Domainid Reponame Repocomment deriving (Show, Eq)
data Perm = PermNone | PermR | PermRW deriving (Show, Eq)
data Permission = Permission Domainname Reponame Username Perm deriving (Show, Eq)
data SshkeyAlgo = SshkeyAlgo String deriving (Show, Eq)
data SshkeyKey = SshkeyKey String deriving (Show, Eq)
data SshkeyComment = SshkeyComment String deriving (Show, Eq)
data Sshkey = Sshkey SshkeyAlgo SshkeyKey SshkeyComment deriving (Show, Eq)
